### ISSUE TITLE
texture locking on direct3d and RGBA/BGRA conversion

### ISSUE THREAD

**Issue by romamik** [Kode/Kore#134]
As I can see user can not detect actual color format, Image::Format only have RGBA32 value. So when making texture.lock() it is impossible to write data with right color format. 
Conversion from RGBA to BGRA is hardcoded in texture constructor. May be we should also convert colors in Texture::unlock()? 

PS Also it's possible to take care of pitch. Currently user can use texture->stride() but at least Kha in image.unlock() does not do this.

**Comment by RobDangerous** [comment]
Fixed by merging #484

**Comment by romamik** [comment]
This is solely your decision, but IMHO my pull request in no way fixes this issues. It works around it in Kha, but the issue is still here.

**Comment by RobDangerous** [comment]
Aye, see my comment at #484
